version: '2'

services:
  app:
    build: .
    container_name: sanic-app
    command: python3 server.py
    volumes:
      - .:/code
    ports:
      - "8002:8000"
    links:
      - postgres:postgreshost
      - redis:redishost
      - elasticsearch:elasticsearchhost
    depends_on:
      - postgres
  postgres:
   image: postgres:9.6.6-alpine
   container_name: sanic-postgres
   environment:
     POSTGRES_DB: andy_app
     PGDATA: /var/lib/postgresql/data/pgdata
   ports:
     - 5432:5432
   logging:
     driver: none
   volumes:
     - /sa_postgre/:/var/www/html
  redis:
    image: redis
    container_name: sanic-redis
    volumes:
      - ~/.sd-redis:/data
    logging:
      driver: none
    ports:
      - "6379:6379"
  adminer:
   image: asergey/adminer:latest
   container_name: sanic-adminer
   environment:
     DB_HOST: postgreshost
     DB_USER: postgres
     DB_PASS: postgres
   ports:
     - 3308:80
   links:
     - postgres:postgreshost
   logging:
     driver: none
  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
   container_name: sanic-elastic-search
   environment:
     - cluster.name=docker-cluster
     - bootstrap.memory_lock=false
     - discovery.zen.minimum_master_nodes=1
     - xpack.security.enabled=false
     - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
   ulimits:
     memlock:
       soft: -1
       hard: -1
   mem_limit: 2g
   ports:
     - 9200:9200
     - 9300:9300
